/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KeyboardHelp: typeof import('./src/components/KeyboardHelp.vue')['default']
    LanguageSwitch: typeof import('./src/components/LanguageSwitch.vue')['default']
    NavigationButtons: typeof import('./src/components/NavigationButtons.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    QuizCard: typeof import('./src/components/QuizCard.vue')['default']
    QuizHeader: typeof import('./src/components/QuizHeader.vue')['default']
    QuizQuestion: typeof import('./src/components/QuizQuestion.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
  }
}
